# Generated by Django 6.0.3 on 2026-03-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="Queue",
            fields=[
                ("name", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("exchange", models.CharField(blank=True, default="", max_length=255)),
                ("routing_key", models.CharField(blank=True, default="", max_length=255)),
                ("consumers", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Queue",
                "verbose_name_plural": "Queues",
                "managed": False,
                "default_permissions": ("view",),
            },
        ),
        migrations.CreateModel(
            name="RegisteredTask",
            fields=[
                ("name", models.CharField(max_length=500, primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "Registered Task",
                "verbose_name_plural": "Registered Tasks",
                "managed": False,
                "default_permissions": ("view",),
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("uuid", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("state", models.CharField(blank=True, default="PENDING", max_length=50)),
                ("worker", models.CharField(blank=True, default="", max_length=255)),
                ("args", models.TextField(blank=True, default="")),
                ("kwargs", models.TextField(blank=True, default="")),
                ("result", models.TextField(blank=True, default="")),
                ("exception", models.TextField(blank=True, default="")),
                ("traceback", models.TextField(blank=True, default="")),
                ("received", models.FloatField(blank=True, null=True)),
                ("started", models.FloatField(blank=True, null=True)),
                ("runtime", models.FloatField(blank=True, null=True)),
                ("eta", models.CharField(blank=True, default="", max_length=255)),
                ("expires", models.CharField(blank=True, default="", max_length=255)),
                ("exchange", models.CharField(blank=True, default="", max_length=255)),
                ("routing_key", models.CharField(blank=True, default="", max_length=255)),
                ("retries", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
                "managed": False,
                "default_permissions": ("view",),
            },
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                ("hostname", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("status", models.CharField(blank=True, default="online", max_length=50)),
                ("active", models.IntegerField(default=0)),
                ("processed", models.IntegerField(blank=True, null=True)),
                ("succeeded", models.IntegerField(blank=True, null=True)),
                ("failed", models.IntegerField(blank=True, null=True)),
                ("retried", models.IntegerField(blank=True, null=True)),
                ("pool", models.CharField(blank=True, default="", max_length=50)),
                ("concurrency", models.IntegerField(blank=True, null=True)),
                ("loadavg", models.CharField(blank=True, default="", max_length=100)),
                ("sw_ident", models.CharField(blank=True, default="", max_length=255)),
                ("sw_ver", models.CharField(blank=True, default="", max_length=255)),
                ("sw_sys", models.CharField(blank=True, default="", max_length=255)),
                ("uptime", models.IntegerField(blank=True, null=True)),
                ("pid", models.IntegerField(blank=True, null=True)),
                ("freq", models.FloatField(default=2.0)),
                ("prefetch_count", models.IntegerField(blank=True, null=True)),
                ("last_heartbeat", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Worker",
                "verbose_name_plural": "Workers",
                "managed": False,
                "default_permissions": ("view",),
            },
        ),
        migrations.CreateModel(
            name="WorkerEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("hostname", models.CharField(max_length=255, unique=True)),
                ("status", models.CharField(default="online", max_length=50)),
                ("active", models.IntegerField(default=0)),
                ("freq", models.FloatField(default=2.0)),
                ("loadavg", models.JSONField(blank=True, default=list)),
                ("sw_ident", models.CharField(blank=True, default="", max_length=255)),
                ("sw_ver", models.CharField(blank=True, default="", max_length=255)),
                ("sw_sys", models.CharField(blank=True, default="", max_length=255)),
                ("last_heartbeat", models.FloatField(blank=True, null=True)),
                ("updated_at", models.FloatField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name="TaskEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.CharField(db_index=True, max_length=255)),
                ("name", models.CharField(blank=True, default="", max_length=500)),
                ("state", models.CharField(db_index=True, max_length=50)),
                ("worker", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                ("args", models.TextField(blank=True, default="")),
                ("kwargs", models.TextField(blank=True, default="")),
                ("result", models.TextField(blank=True, default="")),
                ("exception", models.TextField(blank=True, default="")),
                ("traceback", models.TextField(blank=True, default="")),
                ("runtime", models.FloatField(blank=True, null=True)),
                ("eta", models.CharField(blank=True, default="", max_length=255)),
                ("expires", models.CharField(blank=True, default="", max_length=255)),
                ("exchange", models.CharField(blank=True, default="", max_length=255)),
                ("routing_key", models.CharField(blank=True, default="", max_length=255)),
                ("retries", models.IntegerField(default=0)),
                ("parent_id", models.CharField(blank=True, default="", max_length=255)),
                ("root_id", models.CharField(blank=True, default="", max_length=255)),
                ("received", models.FloatField(blank=True, null=True)),
                ("started", models.FloatField(blank=True, null=True)),
                ("succeeded", models.FloatField(blank=True, null=True)),
                ("failed", models.FloatField(blank=True, null=True)),
                ("retried_at", models.FloatField(blank=True, null=True)),
                ("revoked", models.FloatField(blank=True, null=True)),
                ("updated_at", models.FloatField(db_index=True)),
            ],
            options={
                "indexes": [models.Index(fields=["uuid"], name="celeryx_task_uuid_idx"), models.Index(fields=["-updated_at"], name="celeryx_task_updated_idx")],
            },
        ),
    ]
