# Generated by Django 6.0.3 on 2026-03-16 03:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_celeryx", "0002_remove_taskevent_celeryx_task_uuid_idx_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TaskEvent",
            new_name="TaskState",
        ),
        migrations.RenameModel(
            old_name="WorkerEvent",
            new_name="WorkerState",
        ),
    ]
