# Generated by Django 6.0.3 on 2026-08-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_celeryx", "0003_rename_event_to_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                ("name", models.CharField(max_length=1, primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "Dashboard",
                "verbose_name_plural": "Dashboard",
                "managed": False,
                "default_permissions": ("view",),
            },
        ),
        migrations.AlterModelOptions(
            name="task",
            options={
                "default_permissions": ("view", "change"),
                "managed": False,
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
            },
        ),
        migrations.AlterModelOptions(
            name="worker",
            options={
                "default_permissions": ("view", "change"),
                "managed": False,
                "verbose_name": "Worker",
                "verbose_name_plural": "Workers",
            },
        ),
    ]
